import os

path = r'D:\Ajay\rag\developer-knowledge-base\python\01_basics\20_packages.md'
content = []
content.append("# Packages - __init__.py, subpackages, relative imports")
content.append("")
content.append("## Introduction")
content.append("")
content.append("Packages are directories containing Python modules and a special `__init__.py` file that organize related modules into hierarchical namespaces. They enable logical grouping, prevent naming conflicts, support subpackages for deep hierarchies, and form the basis for distributing reusable code via PyPI. Python 3.3+ also supports namespace packages (directories without `__init__.py`) for splitting a package across multiple directories. Understanding packages is essential for structuring any medium-to-large Python project.")
content.append("")
content.append("## __init__.py")
content.append("")
content.append("### What It Is")
content.append("")
content.append("The `__init__.py` file marks a directory as a Python package. It can be empty or contain package initialization code -- importing submodules, defining `__all__`, setting version info, or running setup logic. When the package is imported, `__init__.py` executes first.")
content.append("")
content.append("### Why It Is Important")
content.append("")
content.append("`__init__.py` controls the package's public API, enabling clean imports like `from package import func` instead of `from package.module import func`. It also allows package-level configuration, lazy loading of submodules, and defining what `from package import *` exports.")
content.append("")
content.append("### How It Works Internally")
content.append("")
content.append("When Python encounters `import package`, it: (1) searches `sys.path` for a directory named `package`; (2) looks for `package/__init__.py` (regular package) or uses namespace package if absent; (3) creates a new module object and executes `__init__.py` in its namespace; (4) the module's `__path__` attribute is set to the package directory path; (5) submodules are not automatically imported unless `__init__.py` imports them.")
content.append("")
content.append("### Syntax")
content.append("")
content.append("```python")
content.append("# package/__init__.py")
content.append('__version__ = "1.0.0"')
content.append('__author__ = "Your Name"')
content.append("from .module1 import func1, func2")
content.append("from .module2 import ClassName")
content.append('__all__ = ["func1", "func2", "ClassName"]')
content.append("```")
content.append("")
content.append("### Beginner Examples")
content.append("")
content.append("```python")
content.append("# mypackage/")
content.append("#   __init__.py")
content.append("#   math_ops.py")
content.append("#   string_ops.py")
content.append("")
content.append("# __init__.py:")
content.append("from .math_ops import add, subtract")
content.append("from .string_ops import reverse")
content.append("")
content.append("# Usage:")
content.append("from mypackage import add, reverse")
content.append("")
content.append("# Minimal __init__.py (empty file)")
content.append("# Just having the file makes the directory importable")
content.append("")
content.append("# With __all__:")
content.append('__all__ = ["add", "subtract", "reverse"]')
content.append("```")
content.append("")
content.append("### Intermediate Examples")
content.append("")
content.append("```python")
content.append("# Conditional imports")
content.append("try:")
content.append("    import numpy as np")
content.append("    HAS_NUMPY = True")
content.append("except ImportError:")
content.append("    HAS_NUMPY = False")
content.append("")
content.append("# Lazy submodule loading")
content.append("class LazyAccess:")
content.append("    def __getattr__(self, name):")
content.append("        import importlib")
content.append('        mod = importlib.import_module(f".{name}", __package__)')
content.append("        setattr(self, name, mod)")
content.append("        return mod")
content.append("")
content.append("import sys")
content.append("sys.modules[__name__] = LazyAccess()")
content.append("")
content.append("# Factory functions")
content.append("def create_engine(url):")
content.append("    from .engines import PostgresEngine, SQLiteEngine")
content.append('    if url.startswith("postgres"):')
content.append("        return PostgresEngine(url)")
content.append("    return SQLiteEngine(url)")
content.append("")
content.append("# Package-level constants")
content.append("DEFAULT_TIMEOUT = 30")
content.append("MAX_RETRIES = 3")
content.append("```")
content.append("")
content.append("### Advanced Examples")
content.append("")
content.append("```python")
content.append("# Automatic submodule discovery")
content.append("import importlib")
content.append("import pkgutil")
content.append("")
content.append("__all__ = []")
content.append("for importer, modname, ispkg in pkgutil.iter_modules(__path__):")
content.append('    if not modname.startswith("_"):')
content.append('        module = importlib.import_module(f".{modname}", __package__)')
content.append("        globals()[modname] = module")
content.append("        __all__.append(modname)")
content.append("")
content.append("# Registry pattern")
content.append("_plugins = {}")
content.append("")
content.append("def register(name):")
content.append("    def decorator(cls):")
content.append("        _plugins[name] = cls")
content.append("        return cls")
content.append("    return decorator")
content.append("")
content.append("def get_plugin(name, *args, **kwargs):")
content.append("    if name not in _plugins:")
content.append('        raise KeyError(f"Plugin {name} not found")')
content.append("    return _plugins[name](*args, **kwargs)")
content.append("```")
content.append("")
content.append("### Real-World Use Cases")
content.append("")
content.append("- Public API surface: Exposing only intended names via __init__.py\n- Version management: Centralized __version__ for the package\n- Plugin systems: Registry pattern\n- Factory functions: Package-level constructors\n- Configuration: Loading config on package import\n- Convenience imports: Making deeply nested modules accessible at top level")
content.append("")
content.append("### Common Mistakes")
content.append("")
content.append("```python")
content.append("# Mistake 1: Expensive operations in __init__.py")
content.append("# __init__.py runs on every import -- keep it fast!")
content.append("# DON'T: import pandas, numpy, tensorflow at top level")
content.append("# DO: lazy imports in functions")
content.append("")
content.append("# Mistake 2: Circular imports in __init__.py")
content.append("# mypackage/__init__.py: from .submodule import X")
content.append("# mypackage/submodule.py: from mypackage import Y")
content.append("# Fix: use lazy imports or restructure")
content.append("")
content.append("# Mistake 3: Forgetting __all__ for import *")
content.append("# Without __all__, import * exports ALL non-underscore names")
content.append("")
content.append("# Mistake 4: Side effects in package initialization")
content.append("# Avoid printing, connecting to databases, etc.")
content.append("```")
content.append("")
content.append("### Best Practices")
content.append("")
content.append("- Keep __init__.py minimal; use lazy imports for heavy dependencies\n- Use __version__ and __author__ for package metadata\n- Define __all__ to control the public API\n- Prefer relative imports in __init__.py\n- Don't put test code or examples in __init__.py\n- Use factory functions instead of importing all submodules eagerly")
content.append("")
content.append("### Performance Considerations")
content.append("")
content.append("Every import of the package executes __init__.py. Heavy imports increase package import time. Use lazy imports (import inside functions) for heavy or rarely-used dependencies.")
content.append("")
content.append("### Interview Questions")
content.append("")
content.append("1. What is the purpose of __init__.py?\n2. Is __init__.py required in Python 3.3+?\n3. What is __all__ and how does it relate to __init__.py?\n4. How do you expose submodule names at the package level?\n5. What should you avoid putting in __init__.py?\n6. How does __init__.py affect import performance?\n7. What is the difference between regular and namespace packages?")
content.append("")
content.append("### Coding Challenges")
content.append("")
content.append("```python")
content.append("# Challenge 1: Auto-discover submodules")
content.append("import importlib")
content.append("import pkgutil")
content.append("")
content.append("def auto_import_submodules(package_path, package_name):")
content.append("    for importer, name, ispkg in pkgutil.iter_modules(package_path):")
content.append('        if not name.startswith("_"):')
content.append('            importlib.import_module(f".{name}", package_name)')
content.append('            print(f"Loaded: {name}")')
content.append("")
content.append("# Challenge 2: Versioned API")
content.append("# __init__.py:")
content.append("__version__ = (1, 0, 0)")
content.append("def get_api_version():")
content.append('    return ".".join(str(v) for v in __version__)')
content.append("")
content.append("# Challenge 3: Lazy package wrapper")
content.append("class LazyPackage:")
content.append("    _modules = {}")
content.append("    def __getattr__(self, name):")
content.append("        import importlib")
content.append("        mod = importlib.import_module(name)")
content.append("        self._modules[name] = mod")
content.append("        return mod")
content.append("import sys; sys.modules[__name__] = LazyPackage()")
content.append("```")
content.append("")
content.append("### Related Topics")
content.append("")
content.append("- Modules vs packages, Subpackages, Relative imports, Namespace packages, PEP 420, pkgutil")
content.append("")
content.append("## Subpackages")
content.append("")
content.append("### What It Is")
content.append("")
content.append("Subpackages are packages nested inside other packages, creating a hierarchical directory structure. They allow deep organization of related functionality (e.g., `package.subpackage.module`). Subpackages have their own `__init__.py` and can be imported using dot notation.")
content.append("")
content.append("### Why It Is Important")
content.append("")
content.append("Subpackages enable logical organization of large codebases -- separating models, views, services, and utilities into distinct namespaces. They prevent naming conflicts in deep hierarchies and mirror the conceptual structure of complex systems.")
content.append("")
content.append("### How It Works Internally")
content.append("")
content.append("Each subpackage is a separate module object with its own `__path__` attribute pointing to its directory. The parent package holds a reference to the subpackage as an attribute (imported explicitly or implicitly). Dot-path resolution (`package.sub.module`) finds the parent, then the subpackage in `parent.__path__`, then the module.")
content.append("")
content.append("### Syntax")
content.append("")
content.append("```python")
content.append("import package.subpackage")
content.append("from package.subpackage import module")
content.append("from package.subpackage.module import function")
content.append("")
content.append("# Structure:")
content.append("# app/")
content.append("#     __init__.py")
content.append("#     models/")
content.append("#         __init__.py")
content.append("#         user.py")
content.append("#     views/")
content.append("#         __init__.py")
content.append("#         user_views.py")
content.append("```")
content.append("")
content.append("### Beginner Examples")
content.append("")
content.append("```python")
content.append("# Hierarchy:")
content.append("# myapp/")
content.append("#     __init__.py")
content.append("#     utils/")
content.append("#         __init__.py")
content.append("#         formatting.py")
content.append("#     database/")
content.append("#         __init__.py")
content.append("#         models/")
content.append("#             __init__.py")
content.append("#             user.py")
content.append("")
content.append("from myapp.utils import formatting")
content.append('print(formatting.format_date("2024-01-15"))')
content.append("")
content.append("from myapp.database.models.user import User")
content.append('user = User("Alice")')
content.append("")
content.append("import myapp.utils.validation")
content.append('myapp.utils.validation.validate_email("test@test.com")')
content.append("```")
content.append("")
content.append("### Intermediate Examples")
content.append("")
content.append("```python")
content.append("# Subpackage __init__.py re-exports")
content.append("# models/__init__.py:")
content.append("from .user import User")
content.append("from .product import Product")
content.append('__all__ = ["User", "Product"]')
content.append("")
content.append("# Users can do:")
content.append("from myapp.database.models import User, Product")
content.append("")
content.append("# Subpackage-level constants")
content.append("# models/__init__.py:")
content.append("DEFAULT_PAGE_SIZE = 20")
content.append("")
content.append("# Factory in subpackage")
content.append("# services/__init__.py:")
content.append("def create_service(name):")
content.append('    if name == "auth":')
content.append("        from .auth import AuthService")
content.append("        return AuthService()")
content.append("")
content.append("# Cross-subpackage imports")
content.append("# services/auth.py:")
content.append("from ..database.models import User  # Relative")
content.append("```")
content.append("")
content.append("### Advanced Examples")
content.append("")
content.append("```python")
content.append("# Dynamic subpackage loading")
content.append("import importlib, pkgutil")
content.append("")
content.append("def load_subpackages(package_name):")
content.append("    package = importlib.import_module(package_name)")
content.append("    results = {}")
content.append('    for imp, modname, ispkg in pkgutil.walk_packages(package.__path__, f"{package_name}."):')
content.append("        results[modname] = importlib.import_module(modname)")
content.append("    return results")
content.append("")
content.append("# Subpackage with __init__ aggregation")
content.append("# services/__init__.py:")
content.append("from .auth import AuthService")
content.append("from .payment import PaymentService")
content.append("")
content.append("class ServiceContainer:")
content.append("    def __init__(self):")
content.append("        self.auth = AuthService()")
content.append("        self.payment = PaymentService()")
content.append("services = ServiceContainer()")
content.append("")
content.append("# Sibling collaboration")
content.append("# models/order.py:")
content.append("from ..services.payment import process_payment")
content.append("")
content.append("def create_order(user, items):")
content.append("    total = sum(item.price for item in items)")
content.append("    process_payment(user, total)")
content.append('    return {"user": user, "items": items, "total": total}')
content.append("```")
content.append("")
content.append("### Real-World Use Cases")
content.append("")
content.append("- Web frameworks: Django/Flask apps with models, views, templates subpackages\n- Library organization: Core, io, utils, models subpackages\n- API versioning: api.v1.users, api.v2.users\n- Plugin systems: plugins.email, plugins.sms, plugins.push\n- Test organization: tests.unit, tests.integration, tests.fixtures")
content.append("")
content.append("### Common Mistakes")
content.append("")
content.append("```python")
content.append("# Mistake 1: Overly deep nesting")
content.append("# package.sub.sub2.sub3.module -- too deep!")
content.append("# Prefer flatter structure with up to 3 levels")
content.append("")
content.append("# Mistake 2: Circular imports between subpackages")
content.append("# services/auth.py: from models import User")
content.append("# models/user.py: from services.auth import authenticate")
content.append("# Fix: Move shared types to common subpackage")
content.append("")
content.append("# Mistake 3: Name collision with standard library")
content.append("# Don't name subpackages 'email', 'json', 'math'")
content.append("# They will shadow standard library modules!")
content.append("```")
content.append("")
content.append("### Best Practices")
content.append("")
content.append("- Limit nesting to 2-3 levels maximum\n- Use meaningful subpackage names (nouns for data, verbs for actions)\n- Re-export key names in parent __init__.py\n- Avoid circular imports between subpackages\n- Use absolute imports for clarity, relative for internal references\n- Keep subpackages loosely coupled\n- Use a `common` or `base` subpackage for shared code")
content.append("")
content.append("### Performance Considerations")
content.append("")
content.append("Each subpackage level adds import overhead (multiple files to find and execute). Subpackage depth has marginal impact on single-import cost but matters for CLI startup time.")
content.append("")
content.append("### Interview Questions")
content.append("")
content.append("1. How do you create a subpackage in Python?\n2. How do you import from a subpackage?\n3. What is the difference between `import package.subpackage` and `from package.subpackage import module`?\n4. How deep should you nest subpackages?\n5. How do you avoid circular imports between sibling subpackages?")
content.append("")
content.append("### Coding Challenges")
content.append("")
content.append("```python")
content.append("# Challenge 1: List subpackages")
content.append("import importlib, pkgutil")
content.append("")
content.append("def list_subpackages(package_name):")
content.append("    package = importlib.import_module(package_name)")
content.append("    return [name for imp, name, ispkg in pkgutil.iter_modules(package.__path__) if ispkg]")
content.append("")
content.append("# Challenge 2: Auto-populate __init__.py")
content.append("import os")
content.append("")
content.append("def populate_init(package_path):")
content.append('    init_file = os.path.join(package_path, "__init__.py")')
content.append("    modules = [f[:-3] for f in os.listdir(package_path)")
content.append('                    if f.endswith(".py") and not f.startswith("_")]')
content.append("    with open(init_file, 'w') as f:")
content.append("        for mod in modules:")
content.append('            f.write(f"from .{mod} import *\\n")')
content.append("")
content.append("# Challenge 3: Cross-subpackage pipeline")
content.append("# services/data_pipeline.py:")
content.append("from ..models.record import Record")
content.append("from ..storage.database import save")
content.append("")
content.append("def process_and_save(raw_data):")
content.append("    record = Record(raw_data)")
content.append("    save(record)")
content.append("    return record")
content.append("```")
content.append("")
content.append("### Related Topics")
content.append("")
content.append("- __init__.py, Relative imports, Package structure, Namespace packages, pkgutil, sys.modules")
content.append("")
content.append("## Relative imports")
content.append("")
content.append("### What It Is")
content.append("")
content.append("Relative imports use dots (`.`) to refer to the current and parent packages within a package hierarchy. A single dot (`.`) means the current package, two dots (`..`) means the parent package, and three dots (`...`) means the grandparent. Relative imports (PEP 328) are the preferred way to import within a package.")
content.append("")
content.append("### Why It Is Important")
content.append("")
content.append("Relative imports make intra-package imports resilient to package renaming -- you can change the top-level package name without updating internal imports. They also make code more self-documenting by showing the relationship between modules.")
content.append("")
content.append("### How It Works Internally")
content.append("")
content.append("Relative imports resolve using the `__package__` attribute of the importing module. Python computes the absolute module path by combining the current `__package__` with the relative reference. For example, in `package.sub.module` with `from ..sibling import func`, Python calculates the target as `package.sibling`. Relative imports only work when the module's `__package__` is set (i.e., when it's being imported as part of a package, not executed directly).")
content.append("")
content.append("### Syntax")
content.append("")
content.append("```python")
content.append("from . import sibling_module")
content.append("from .module import name")
content.append("from .. import parent_module")
content.append("from ..parent_module import name")
content.append("from .subpackage.module import func")
content.append("from ..sibling.module import name")
content.append("")
content.append("# Invalid (cannot go above top-level package):")
content.append("# from ... import something  # Too many dots")
content.append("```")
content.append("")
content.append("### Beginner Examples")
content.append("")
content.append("```python")
content.append("# Package structure:")
content.append("# mypackage/")
content.append("#     __init__.py")
content.append("#     utils.py")
content.append("#     helpers.py")
content.append("#     subpackage/")
content.append("#         __init__.py")
content.append("#         module.py")
content.append("")
content.append("# utils.py imports from sibling:")
content.append("from . import helpers  # Import sibling module")
content.append("from .helpers import format_output")
content.append("")
content.append("# subpackage/module.py imports from parent:")
content.append("from .. import utils")
content.append("from ..utils import process_data")
content.append("from . import sibling_module  # Same subpackage")
content.append("")
content.append("# Cannot use relative imports when running directly:")
content.append("# python mypackage/utils.py  # Error!")
content.append("# Use: python -m mypackage.utils")
content.append("```")
content.append("")
content.append("### Intermediate Examples")
content.append("")
content.append("```python")
content.append("# Deep relative imports")
content.append("# Structure:")
content.append("# app/")
content.append("#     __init__.py")
content.append("#     models/")
content.append("#         __init__.py")
content.append("#         user.py")
content.append("#     services/")
content.append("#         __init__.py")
content.append("#         auth.py")
content.append("#         subservices/")
content.append("#             __init__.py")
content.append("#             features.py")
content.append("")
content.append("# services/subservices/features.py:")
content.append("from ...models.user import User  # 3 levels up to app, then down")
content.append("from ..auth import authenticate  # 2 levels up to services, then sibling")
content.append("from . import __init__  # Same package")
content.append("")
content.append("# Versus absolute:")
content.append("from app.models.user import User")
content.append("")
content.append("# Relative imports in __init__.py")
content.append("# models/__init__.py:")
content.append("from .user import User")
content.append("from .product import Product")
content.append("")
content.append("# Lazy relative import")
content.append("def get_user_model():")
content.append("    from .user import User")
content.append("    return User")
content.append("```")
content.append("")
content.append("### Advanced Examples")
content.append("")
content.append("```python")
content.append("# Dynamic relative imports")
content.append("import importlib")
content.append("")
content.append("def import_sibling(name):")
content.append("    return importlib.import_module(f'.{name}', __package__)")
content.append("")
content.append("# Safe relative import with error handling")
content.append("try:")
content.append("    from .local_config import settings")
content.append("except ImportError:")
content.append("    from ..shared_config import settings")
content.append("")
content.append("# __init__.py as import hub")
content.append("# services/__init__.py:")
content.append("from .auth import AuthService")
content.append("from .payment import PaymentService")
content.append("from .email import EmailService")
content.append("")
content.append("# Relative imports with __all__")
content.append("from .user import User")
content.append("from .product import Product")
content.append('__all__ = ["User", "Product"]')
content.append("")
content.append("# Resolving __package__ for debugging")
content.append("import sys")
content.append('print(f"Current package: {__package__}")')
content.append("")
content.append("# Test relative imports in a package:")
content.append("# python -m mypackage.subpackage.module  # Works")
content.append("# python mypackage/subpackage/module.py  # Fails (__package__ is None)")
content.append("```")
content.append("")
content.append("### Real-World Use Cases")
content.append("")
content.append("- Internal module references within packages\n- Models importing from services and vice versa (sibling imports)\n- Test files importing from source modules\n- Plugin modules referencing the core package\n- Versioned API subpackages referencing shared base\n- Utility functions importing from sibling modules")
content.append("")
content.append("### Common Mistakes")
content.append("")
content.append("```python")
content.append("# Mistake 1: Running module with relative imports directly")
content.append("# python package/module.py  # ImportError: attempted relative import")
content.append("# Fix: python -m package.module")
content.append("")
content.append("# Mistake 2: Going beyond top-level package")
content.append("# from ....module import func  # ValueError: too many dots")
content.append("# Maximum dots = number of parent levels in the package")
content.append("")
content.append("# Mistake 3: Mixing absolute and relative imports")
content.append("# This is fine, but prefer consistency within a package")
content.append("from ..utils import helper  # relative")
content.append("from mypackage.database import models  # absolute")
content.append("")
content.append("# Mistake 4: Relative import in __main__")
content.append("# When __name__ == '__main__', __package__ is None")
content.append("# Can't use relative imports in the entry point script")
content.append("")
content.append("# Mistake 5: Forgetting __init__.py for relative imports")
content.append("# Python 3.3+ namespace packages work, but __init__.py is safer")
content.append("```")
content.append("")
content.append("### Best Practices")
content.append("")
content.append("- Use relative imports for all internal package references\n- Use absolute imports for cross-package references\n- Never use relative imports in standalone scripts\n- Run package code with `python -m` to support relative imports\n- Keep import paths shallow (avoid deep relative chains)\n- Be consistent -- pick one style per package\n- Document the package structure if relative paths are complex")
content.append("")
content.append("### Performance Considerations")
content.append("")
content.append("Relative imports resolve at the same speed as absolute imports -- the `__package__` attribute provides the current module path. The resolution happens once at module load time. There is no runtime overhead difference between relative and absolute imports.")
content.append("")
content.append("### Interview Questions")
content.append("")
content.append("1. What is the syntax for relative imports?\n2. Why can't you use relative imports in scripts run directly?\n3. What is __package__ and how does it enable relative imports?\n4. How many dots can you use in a relative import?\n5. What is the difference between `from . import x` and `from .. import y`?\n6. Why are relative imports preferred within packages?\n7. What happens with `python -m package.module` vs `python package/module.py`?")
content.append("")
content.append("### Coding Challenges")
content.append("")
content.append("```python")
content.append("# Challenge 1: Package-aware import function")
content.append("def package_aware_import(module_path):")
content.append("    if module_path.startswith('.'):")
content.append("        return importlib.import_module(module_path, __package__)")
content.append("    return importlib.import_module(module_path)")
content.append("")
content.append("# Challenge 2: Import resolver")
content.append("def resolve_relative_import(current_file, relative_path):")
content.append("    import importlib")
content.append("    pkg = importlib.import_module(current_file)")
content.append("    return importlib.import_module(relative_path, pkg.__package__)")
content.append("")
content.append("# Challenge 3: Safe relative importer")
content.append("def safe_relative_import(name):")
content.append("    if __package__ is None:")
content.append("        raise ImportError('__package__ is None -- cannot use relative import')")
content.append("    return importlib.import_module(f'.{name}', __package__)")
content.append("")
content.append("# Challenge 4: Create a package structure programmatically")
content.append("def create_package_structure(base_path, structure):")
content.append("    import os")
content.append("    for path, content in structure.items():")
content.append("        full_path = os.path.join(base_path, *path.split('/'))")
content.append("        os.makedirs(os.path.dirname(full_path), exist_ok=True)")
content.append("        with open(full_path, 'w') as f:")
content.append("            f.write(content)")
content.append("")
content.append("# Example structure:")
content.append("structure = {")
content.append('    "__init__.py": "from .core import handle\\n",')
content.append('    "core.py": "def handle(): return 42\\n",')
content.append('    "sub/__init__.py": ("from ..core import handle\\n" "def process(): return handle() + 1\\n"),')
content.append("}")
content.append("# create_package_structure('/tmp/mypkg', structure)")
content.append("```")
content.append("")
content.append("### Related Topics")
content.append("")
content.append("- __init__.py, Subpackages, Package structure, Absolute imports, __package__, python -m, sys.modules, importlib")
content.append("")

with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(content))
print(f"Written {len(content)} lines to {path}")
