import sys, os

content = []
content.append("# Type Casting - int(), float(), str(), bool(), explicit conversion")
content.append("")
content.append("## Introduction")
content.append("")
content.append("Type casting (type conversion) transforms a value from one data type to another. Python supports implicit conversion (automatic widening by the interpreter) and explicit conversion using built-in functions like int(), float(), str(), bool(), list(), tuple(), set(), and dict(). Understanding both forms is critical for handling user input, data serialization, arithmetic operations, and interop between libraries.")
content.append("")
content.append("## int() conversion")
content.append("")
content.append("### What It Is")
content.append("")
content.append("int(x, base=10) converts a number or string to an integer. It accepts ints, floats (truncates toward zero), strings (with optional base), bytes, and objects implementing __int__().")
content.append("")
content.append("### Why It Is Important")
content.append("")
content.append("Integer conversion is essential for processing user input, parsing configuration values, working with indices, performing exact arithmetic, and converting floating-point data to discrete values.")
content.append("")
content.append("### How It Works Internally")
content.append("")
content.append("For strings, int() calls PyLong_FromString(), which parses the C string, handles sign and base prefix detection. For floats, PyLong_FromDouble() truncates toward zero. For other objects, int() calls the __int__() slot if defined, else __index__().")
content.append("")
content.append("### Syntax")
content.append("")
content.append("```python")
content.append('i = int("42")')
content.append('i = int("1010", 2)    # 10 (binary)')
content.append('i = int("FF", 16)     # 255 (hex)')
content.append('i = int("0xFF", 0)    # 255 (auto-detect base)')
content.append("i = int(3.14)         # 3 (truncates)")
content.append("```")
content.append("")
content.append("### Beginner Examples")
content.append("")
content.append("```python")
content.append('age = int("30")')
content.append("print(age + 10)  # 40")
content.append("print(int(3.99))   # 3")
content.append("print(int(-3.99))  # -3")
content.append("print(int(True))   # 1")
content.append('print(int("1010", 2))  # 10')
content.append("```")
content.append("")
content.append("### Intermediate Examples")
content.append("")
content.append("```python")
content.append("def safe_int(value, default=0):")
content.append("    try:")
content.append("        return int(value)")
content.append("    except (ValueError, TypeError):")
content.append("        return default")
content.append("")
content.append("class Score:")
content.append("    def __init__(self, value):")
content.append("        self.value = value")
content.append("    def __int__(self):")
content.append("        return int(self.value * 100)")
content.append("")
content.append("print(int(Score(0.95)))  # 95")
content.append("```")
content.append("")
content.append("### Advanced Examples")
content.append("")
content.append("```python")
content.append('nums = list(map(int, ["1", "2", "3"]))')
content.append("print(nums)  # [1, 2, 3]")
content.append('huge = int("1" + "0" * 1000)')
content.append("print(huge.bit_length())  # 3322 bits (no overflow)")
content.append("```")
content.append("")
content.append("### Real-World Use Cases")
content.append("")
content.append("User input conversion, config parsing, CSV/JSON integer fields, ID normalization, base conversion.")
content.append("")
content.append("### Common Mistakes")
content.append("")
content.append("```python")
content.append('# int("3.14")  # ValueError')
content.append("print(int(-3.9))   # -3 (truncation toward zero)")
content.append("import math")
content.append("print(math.floor(-3.9))  # -4 (floor is different)")
content.append('# int(None)  # TypeError')
content.append('# int("")    # ValueError')
content.append("```")
content.append("")
content.append("### Best Practices")
content.append("")
content.append("Wrap in try/except ValueError; use int(x, 0) for auto base detection; use map(int, seq) for bulk conversion.")
content.append("")
content.append("### Performance Considerations")
content.append("")
content.append("O(n) for string conversion (n = digits), O(1) for float. Python ints are arbitrary-precision (no overflow).")
content.append("")
content.append("### Interview Questions")
content.append("")
content.append("1. What happens with int(\"3.14\")?")
content.append("2. How does int() handle different bases?")
content.append("3. What is the difference between int(-3.9) and math.floor(-3.9)?")
content.append("4. Can int() overflow in Python?")
content.append("5. What is the __int__ dunder method used for?")
content.append("")
content.append("### Coding Challenges")
content.append("")
content.append("```python")
content.append("def roman_to_int(s):")
content.append('    values = {"I": 1, "V": 5, "X": 10, "L": 50, "C": 100, "D": 500, "M": 1000}')
content.append("    total, prev = 0, 0")
content.append("    for c in reversed(s):")
content.append("        curr = values[c]")
content.append("        total += -curr if curr < prev else curr")
content.append("        prev = curr")
content.append("    return total")
content.append("")
content.append('print(roman_to_int("XIV"))       # 14')
content.append('print(roman_to_int("MCMXCIV"))   # 1994')
content.append("")
content.append("def binary_to_int(s):")
content.append("    result = 0")
content.append("    for c in s:")
content.append('        result = result * 2 + (c == "1")')
content.append("    return result")
content.append("")
content.append('print(binary_to_int("1010"))  # 10')
content.append("```")
content.append("")
content.append("### Related Topics")
content.append("")
content.append("- float() conversion, str() conversion, math.floor/ceil, __int__/__index__ dunder methods")
content.append("")
content.append("## float() conversion")
content.append("")
content.append("### What It Is")
content.append("")
content.append("float(x) converts to double-precision floating-point (64-bit IEEE 754). Accepts ints, strings, bytes, and objects with __float__().")
content.append("")
content.append("### Why It Is Important")
content.append("")
content.append("Float conversion is essential for scientific computing, user-supplied measurements, parsing decimal data, and any domain requiring fractional values.")
content.append("")
content.append("### How It Works Internally")
content.append("")
content.append("float() calls PyFloat_FromString() which uses strtod() for parsing, supporting scientific notation, inf, and NaN. For ints, PyFloat_FromDouble() converts the Python int to a C double (may lose precision for very large ints).")
content.append("")
content.append("### Syntax")
content.append("")
content.append("```python")
content.append('f = float("3.14")')
content.append('f = float("1e-3")      # 0.001')
content.append('f = float("inf")')
content.append('f = float("nan")')
content.append("f = float(42)          # 42.0")
content.append("f = float(True)        # 1.0")
content.append("```")
content.append("")
content.append("### Beginner Examples")
content.append("")
content.append("```python")
content.append('price = float("19.99")')
content.append("print(price + 0.01)  # 20.0")
content.append("print(float(10))     # 10.0")
content.append('print(float("1e6"))  # 1000000.0')
content.append('print(float("inf"))  # inf')
content.append('print(float("nan"))  # nan')
content.append("```")
content.append("")
content.append("### Intermediate Examples")
content.append("")
content.append("```python")
content.append("def safe_float(value, default=0.0):")
content.append("    try:")
content.append("        return float(value)")
content.append("    except (ValueError, TypeError):")
content.append("        return default")
content.append("")
content.append("class Temperature:")
content.append("    def __init__(self, celsius):")
content.append("        self.celsius = celsius")
content.append("    def __float__(self):")
content.append("        return float(self.celsius)")
content.append("")
content.append("print(float(Temperature(23.5)))  # 23.5")
content.append("")
content.append('data = ["1.5", "2.7", "3.14"]')
content.append("floats = list(map(float, data))")
content.append("print(floats)  # [1.5, 2.7, 3.14]")
content.append("```")
content.append("")
content.append("### Advanced Examples")
content.append("")
content.append("```python")
content.append("print(0.1 + 0.2)  # 0.30000000000000004 (IEEE 754)")
content.append("print(0.1 + 0.2 == 0.3)  # False!")
content.append("print(abs((0.1 + 0.2) - 0.3) < 1e-9)  # True (tolerance)")
content.append("")
content.append("def clean_floats(dataset):")
content.append("    if isinstance(dataset, list):")
content.append("        return [clean_floats(item) for item in dataset]")
content.append("    if isinstance(dataset, str):")
content.append("        try:")
content.append("            return float(dataset)")
content.append("        except ValueError:")
content.append("            return dataset")
content.append("    return dataset")
content.append("")
content.append('messy = ["3.14", "abc", "1e3"]')
content.append("print(clean_floats(messy))  # [3.14, 'abc', 1000.0]")
content.append("```")
content.append("")
content.append("### Real-World Use Cases")
content.append("")
content.append("Scientific measurements, config thresholds, JSON float fields, CSV price/weight columns.")
content.append("")
content.append("### Common Mistakes")
content.append("")
content.append("```python")
content.append("print(0.1 + 0.2)  # 0.30000000000000004")
content.append("print(0.1 + 0.2 == 0.3)  # False!")
content.append('# float("$3.14")  # ValueError -- strip symbols first')
content.append("print(float(10**1000))  # inf (overflow to infinity)")
content.append("```")
content.append("")
content.append("### Best Practices")
content.append("")
content.append("Use Decimal for financial calculations; use math.isclose() for float equality.")
content.append("")
content.append("### Performance Considerations")
content.append("")
content.append("float() is O(1) for ints, O(n) for string length. Decimal is significantly slower but exact.")
content.append("")
content.append("### Interview Questions")
content.append("")
content.append("1. Why is 0.1 + 0.2 != 0.3?")
content.append("2. How does Python represent floats internally?")
content.append("3. What does float(\"inf\") return?")
content.append("4. What happens when converting a very large int to float?")
content.append("")
content.append("### Coding Challenges")
content.append("")
content.append("```python")
content.append('def parse_currency(s):')
content.append('    return float(s.replace("$", "").replace(",", ""))')
content.append("")
content.append('print(parse_currency("$1,234.56"))  # 1234.56')
content.append("")
content.append("def celsius_to_fahrenheit(c):")
content.append("    return float(c) * 9/5 + 32")
content.append("")
content.append('print(celsius_to_fahrenheit("100"))  # 212.0')
content.append("```")
content.append("")
content.append("### Related Topics")
content.append("")
content.append("- int() conversion, decimal.Decimal, math.isclose(), IEEE 754")
content.append("")
content.append("## str() conversion")
content.append("")
content.append("### What It Is")
content.append("")
content.append("str(object) returns a string representation. Calls __str__() first, falling back to __repr__().")
content.append("")
content.append("### Why It Is Important")
content.append("")
content.append("String conversion is the most common type conversion -- used for output, concatenation, logging, serialization.")
content.append("")
content.append("### How It Works Internally")
content.append("")
content.append("Checks for __str__() method; if not defined, uses __repr__(). For bytes, accepts encoding parameter.")
content.append("")
content.append("### Syntax")
content.append("")
content.append("```python")
content.append('s = str(42)        # "42"')
content.append('s = str(3.14)      # "3.14"')
content.append('s = str([1, 2])   # "[1, 2]"')
content.append('s = str(True)     # "True"')
content.append('s = str(None)     # "None"')
content.append("```")
content.append("")
content.append("### Beginner Examples")
content.append("")
content.append("```python")
content.append('count = 42')
content.append('message = "Count: " + str(count)')
content.append("print(message)  # Count: 42")
content.append("")
content.append("print(str(3.14))    # 3.14")
content.append("print(str(True))    # True")
content.append("print(str(None))    # None")
content.append("print(str([1, 2]))  # [1, 2]")
content.append("")
content.append('# Without str(), concatenation fails')
content.append('# "Value: " + 42  # TypeError')
content.append("```")
content.append("")
content.append("### Intermediate Examples")
content.append("")
content.append("```python")
content.append("class Person:")
content.append("    def __init__(self, name, age):")
content.append("        self.name = name")
content.append("        self.age = age")
content.append("    def __str__(self):")
content.append('        return f"{self.name}, {self.age}yo"')
content.append("    def __repr__(self):")
content.append('        return f"Person({self.name!r}, {self.age})"')
content.append("")
content.append("p = Person('Alice', 30)")
content.append("print(str(p))   # Alice, 30yo")
content.append("print(repr(p))  # Person('Alice', 30)")
content.append("")
content.append("import datetime")
content.append("d = datetime.datetime(2024, 1, 15)")
content.append("print(str(d))   # 2024-01-15 00:00:00")
content.append("print(repr(d))  # datetime.datetime(2024, 1, 15, 0, 0)")
content.append("```")
content.append("")
content.append("### Advanced Examples")
content.append("")
content.append("```python")
content.append('data = b"hello"')
content.append('s = str(data, "utf-8")')
content.append("print(s)  # hello")
content.append("")
content.append("class Report:")
content.append("    def __init__(self, title, data):")
content.append("        self.title = title")
content.append("        self.data = data")
content.append("    def __str__(self):")
content.append('        lines = [f"Report: {self.title}"]')
content.append('        for k, v in self.data.items():')
content.append('            lines.append(f"  {k}: {v}")')
content.append('        return "\\n".join(lines)')
content.append("")
content.append('r = Report("Sales", {"Q1": 100, "Q2": 200})')
content.append("print(str(r))")
content.append("```")
content.append("")
content.append("### Real-World Use Cases")
content.append("")
content.append("String formatting, logging, serialization, user-facing display, error messages.")
content.append("")
content.append("### Common Mistakes")
content.append("")
content.append("```python")
content.append('s = "hello\\nworld"')
content.append("print(str(s))   # hello (newline) world")
content.append("print(repr(s))  # 'hello\\\\nworld' (escaped)")
content.append("")
content.append('# str() on bytes without encoding')
content.append('print(str(b"\\\\xc3\\\\xa9"))  # b\'\\\\xc3\\\\xa9\'')
content.append('print(str(b"\\\\xc3\\\\xa9", "utf-8"))  # Correct')
content.append("```")
content.append("")
content.append("### Best Practices")
content.append("")
content.append("Implement __str__ for display, __repr__ for debugging; use f-strings over str() concatenation.")
content.append("")
content.append("### Performance Considerations")
content.append("")
content.append("str() is O(n) for the string length. Custom __str__() complexity depends on implementation.")
content.append("")
content.append("### Interview Questions")
content.append("")
content.append("1. What is the difference between __str__ and __repr__?")
content.append("2. How do you convert bytes to a string?")
content.append("3. What is the default str() behavior for objects?")
content.append("")
content.append("### Coding Challenges")
content.append("")
content.append("```python")
content.append("class Color:")
content.append("    def __init__(self, r, g, b):")
content.append("        self.r, self.g, self.b = r, g, b")
content.append("    def __str__(self):")
content.append('        return f"rgb({self.r}, {self.g}, {self.b})"')
content.append("    def __repr__(self):")
content.append('        return f"Color({self.r}, {self.g}, {self.b})"')
content.append("")
content.append("c = Color(255, 128, 64)")
content.append("print(str(c))   # rgb(255, 128, 64)")
content.append("print(repr(c))  # Color(255, 128, 64)")
content.append("")
content.append('def str_join(items, sep=", "):')
content.append("    return sep.join(str(item) for item in items)")
content.append("")
content.append('print(str_join([1, "hello", 3.14]))  # 1, hello, 3.14')
content.append("```")
content.append("")
content.append("### Related Topics")
content.append("")
content.append("- repr() built-in, __str__ vs __repr__, encode()/decode()")
content.append("")
content.append("## bool() conversion")
content.append("")
content.append("### What It Is")
content.append("")
content.append("bool(x) converts to True or False. Falsy values: None, False, zero numerics, empty collections/strings. Everything else is True.")
content.append("")
content.append("### Why It Is Important")
content.append("")
content.append("Used in truthiness testing for conditionals, filtering, and logical operations. Understanding what converts to False prevents subtle bugs.")
content.append("")
content.append("### How It Works Internally")
content.append("")
content.append("CPython's PyObject_IsTrue(): checks None/False returns False; numeric returns x != 0; __len__() returns len != 0; __bool__() if defined; otherwise True.")
content.append("")
content.append("### Syntax")
content.append("")
content.append("```python")
content.append("b = bool(0)        # False")
content.append("b = bool(1)        # True")
content.append('b = bool("")       # False')
content.append('b = bool("hello")  # True')
content.append("b = bool([])       # False")
content.append("b = bool(None)     # False")
content.append("```")
content.append("")
content.append("### Beginner Examples")
content.append("")
content.append("```python")
content.append("print(bool(False))    # False")
content.append("print(bool(0))        # False")
content.append("print(bool(0.0))      # False")
content.append('print(bool(""))       # False')
content.append("print(bool([]))       # False")
content.append("print(bool({}))       # False")
content.append("print(bool(None))     # False")
content.append("print(bool(1))        # True")
content.append("print(bool(-1))       # True")
content.append('print(bool([0]))      # True (non-empty list)')
content.append('print(bool("False"))  # True! (non-empty string)')
content.append("```")
content.append("")
content.append("### Intermediate Examples")
content.append("")
content.append("```python")
content.append('print(bool("False"))  # True -- common gotcha!')
content.append("")
content.append("def str_to_bool(s):")
content.append('    return s.lower() in ("true", "yes", "1", "y")')
content.append("")
content.append('print(str_to_bool("True"))   # True')
content.append('print(str_to_bool("false"))  # False')
content.append("")
content.append("class Account:")
content.append("    def __init__(self, balance):")
content.append("        self.balance = balance")
content.append("    def __bool__(self):")
content.append("        return self.balance > 0")
content.append("")
content.append("print(bool(Account(100)))  # True")
content.append("print(bool(Account(0)))    # False")
content.append("")
content.append('# Using bool for filtering')
content.append('items = [0, 1, "", "hello", None, [], [1]]')
content.append("truthy = [x for x in items if bool(x)]")
content.append("print(truthy)  # [1, 'hello', [1]]")
content.append("```")
content.append("")
content.append("### Advanced Examples")
content.append("")
content.append("```python")
content.append("class Team:")
content.append("    def __init__(self, members):")
content.append("        self.members = members")
content.append("    def __len__(self):")
content.append("        return len(self.members)")
content.append("")
content.append("t1 = Team(['Alice', 'Bob'])")
content.append("t2 = Team([])")
content.append("print(bool(t1))  # True")
content.append("print(bool(t2))  # False")
content.append("")
content.append("# Numeric bool behavior")
content.append("print(bool(0))      # False")
content.append("print(bool(0.0))    # False")
content.append("print(bool(1))      # True")
content.append("print(bool(-1))     # True")
content.append("```")
content.append("")
content.append("### Real-World Use Cases")
content.append("")
content.append("Conditional checks, data validation, filtering falsy values, flag parsing, object state checks.")
content.append("")
content.append("### Common Mistakes")
content.append("")
content.append("```python")
content.append('print(bool("False"))  # True (non-empty string is always True)')
content.append("# Use str_to_bool() for string parsing")
content.append("")
content.append("print(bool([]))     # False")
content.append("print(bool([[]]))   # True (non-empty list containing empty list)")
content.append("")
content.append("# if bool(x): is same as if x:")
content.append("# Prefer: if x:")
content.append("```")
content.append("")
content.append("### Best Practices")
content.append("")
content.append("Use 'if x:' not 'if bool(x):'; implement __bool__ for custom truthiness; use explicit string parsing for boolean strings.")
content.append("")
content.append("### Performance Considerations")
content.append("")
content.append("bool() is extremely fast -- just a pointer check and optionally a method call. 'if x:' implicitly calls bool().")
content.append("")
content.append("### Interview Questions")
content.append("")
content.append("1. What values are falsy in Python?")
content.append('2. Why is bool("False") True?')
content.append("3. How is bool related to int?")
content.append("4. What is the difference between __bool__ and __len__?")
content.append("")
content.append("### Coding Challenges")
content.append("")
content.append("```python")
content.append("def safe_bool(value):")
content.append("    if isinstance(value, str):")
content.append('        return value.lower() in ("true", "yes", "1", "y")')
content.append("    return bool(value)")
content.append("")
content.append('print(safe_bool("True"))    # True')
content.append('print(safe_bool("false"))   # False')
content.append("print(safe_bool(1))         # True")
content.append("")
content.append("def all_true(iterable):")
content.append("    return all(iterable)")
content.append("")
content.append('print(all_true([1, "hello", [1]]))   # True')
content.append('print(all_true([1, "", [1]]))        # False')
content.append("```")
content.append("")
content.append("### Related Topics")
content.append("")
content.append("- Truthiness, __bool__ vs __len__, all()/any() built-ins, short-circuit evaluation")
content.append("")
content.append("## Explicit conversion")
content.append("")
content.append("### What It Is")
content.append("")
content.append("Explicit conversion (casting) uses built-in functions: list(), tuple(), set(), dict(), frozenset(), complex(), bytes(), bytearray().")
content.append("")
content.append("### Why It Is Important")
content.append("")
content.append("Python rarely performs implicit cross-type conversions beyond numeric widening. Strings must be explicitly parsed, collections must be explicitly converted.")
content.append("")
content.append("### How It Works Internally")
content.append("")
content.append("Each converter: checks if already target type; for strings, parses; for collections, iterates and constructs new collection; for custom types, calls appropriate dunder method.")
content.append("")
content.append("### Syntax")
content.append("")
content.append("```python")
content.append("list('hello')       # ['h', 'e', 'l', 'l', 'o']")
content.append("tuple([1, 2, 3])    # (1, 2, 3)")
content.append("set([1, 2, 2, 3])   # {1, 2, 3}")
content.append("dict([('a', 1)])    # {'a': 1}")
content.append("frozenset([1, 2])")
content.append("bytes([65, 66])     # b'AB'")
content.append("complex(1, 2)       # (1+2j)")
content.append("```")
content.append("")
content.append("### Beginner Examples")
content.append("")
content.append("```python")
content.append("text = 'hello'")
content.append("chars = list(text)")
content.append("print(chars)  # ['h', 'e', 'l', 'l', 'o']")
content.append("")
content.append("fruits = ['apple', 'banana']")
content.append("fruits_t = tuple(fruits)")
content.append("print(fruits_t)  # ('apple', 'banana')")
content.append("")
content.append("numbers = [1, 2, 2, 3]")
content.append("unique = set(numbers)")
content.append("print(unique)  # {1, 2, 3}")
content.append("")
content.append("pairs = [('a', 1), ('b', 2)]")
content.append("d = dict(pairs)")
content.append("print(d)  # {'a': 1, 'b': 2}")
content.append("```")
content.append("")
content.append("### Intermediate Examples")
content.append("")
content.append("```python")
content.append('matrix_str = "1 2 3; 4 5 6; 7 8 9"')
content.append('rows = matrix_str.split(";")')
content.append("matrix = [list(map(int, row.split())) for row in rows]")
content.append("print(matrix)  # [[1, 2, 3], [4, 5, 6], [7, 8, 9]]")
content.append("")
content.append("data = bytes([65, 66, 67])")
content.append("print(data)  # b'ABC'")
content.append("")
content.append("c = complex('3+4j')")
content.append("print(c)  # (3+4j)")
content.append("```")
content.append("")
content.append("### Advanced Examples")
content.append("")
content.append("```python")
content.append("def convert(value, target_type, default=None):")
content.append("    try:")
content.append("        if target_type == int:")
content.append("            return int(value)")
content.append("        elif target_type == float:")
content.append("            return float(value)")
content.append("        elif target_type == str:")
content.append("            return str(value)")
content.append("        elif target_type == bool and isinstance(value, str):")
content.append('            return value.lower() in ("true", "yes", "1", "y")')
content.append("    except (ValueError, TypeError):")
content.append("        return default")
content.append("")
content.append('print(convert("42", int))       # 42')
content.append('print(convert("true", bool))    # True')
content.append("")
content.append("def infer_type(value):")
content.append("    if value is None:")
content.append("        return None")
content.append("    try:")
content.append('        return int(value) if "." not in value else float(value)')
content.append("    except (ValueError, TypeError):")
content.append('        return value.lower() in ("true", "false") if isinstance(value, str) else value')
content.append("```")
content.append("")
content.append("### Real-World Use Cases")
content.append("")
content.append("CSV/JSON parsing, data cleaning, API response conversion, config parsing, ETL pipelines.")
content.append("")
content.append("### Common Mistakes")
content.append("")
content.append("```python")
content.append("print(list('hello'))       # ['h', 'e', 'l', 'l', 'o']")
content.append("print('hello'.split())     # ['hello'] -- different!")
content.append("# set([[1, 2], [3, 4]])   # TypeError (unhashable)")
content.append("# dict([1, 2, 3])          # ValueError (not pairs)")
content.append("```")
content.append("")
content.append("### Best Practices")
content.append("")
content.append("Use explicit conversion; handle errors with try/except; use map(type_func, data) for bulk conversion.")
content.append("")
content.append("### Performance Considerations")
content.append("")
content.append("list()/tuple() on existing collection: O(n) shallow copy. set() deduplicates O(n). dict() on pairs O(n).")
content.append("")
content.append("### Interview Questions")
content.append("")
content.append("1. How do you convert a list of tuples to a dictionary?")
content.append("2. Why is list('hello') different from 'hello'.split()?")
content.append("3. What happens with dict() on a list of 2-element lists?")
content.append("4. How do you safely convert a value to multiple types?")
content.append("")
content.append("### Coding Challenges")
content.append("")
content.append("```python")
content.append("def convert_row(headers, values, types):")
content.append("    return {h: types[i](v) for i, (h, v) in enumerate(zip(headers, values))}")
content.append("")
content.append('headers = ["name", "age", "score"]')
content.append('row = ["Alice", "30", "95.5"]')
content.append("types = [str, int, float]")
content.append("print(convert_row(headers, row, types))")
content.append("")
content.append("def flatten_and_convert(nested):")
content.append("    result = []")
content.append("    for item in nested:")
content.append("        if isinstance(item, (list, tuple)):")
content.append("            result.extend(flatten_and_convert(item))")
content.append("        else:")
content.append("            result.append(item)")
content.append("    return result")
content.append("")
content.append('nested = [[1, 2], (3, "4"), [5, 6.0]]')
content.append("flat = flatten_and_convert(nested)")
content.append("print(flat)  # [1, 2, 3, '4', 5, 6.0]")
content.append("```")
content.append("")
content.append("### Related Topics")
content.append("")
content.append("- int(), float(), str(), bool() conversions; list(), tuple(), set(), dict() constructors; type coercion vs conversion")

path = r'D:\Ajay\rag\developer-knowledge-base\python\01_basics\15_type_casting.md'
with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(content))
print(f"Written {len(content)} lines to {path}")
